const mengsanConfig = {
    modeId: "mengsan_shuying",
    saveKey: "mengsan_run_shuying",
    profileKey: "mengsan_profile_shuying",
    schemaVersion: 1,
    mapLayoutVersion: 3,
    routeCount: 4,
    characters: ["re_zhaoyun", "sunquan", "re_huangyueying", "re_zhangfei"],
    acts: [
        {
            id: "act1",
            name: "第一关·初梦",
            floorNodes: [1, 4, 4, 4, 1],
            minFloorNodes: [1, 3, 3, 3, 1],
            nodeWeights: { battle: 65, event: 15, rest: 10, shop: 10 },
            enemies: ["re_xiahoudun", "re_zhangliao", "re_xuzhu"],
            boss: "re_lvbu",
            baseGold: 20,
        },
        {
            id: "act2",
            name: "第二关·迷梦",
            floorNodes: [1, 4, 4, 4, 4, 1],
            minFloorNodes: [1, 3, 2, 3, 3, 1],
            nodeWeights: { battle: 55, elite: 15, event: 12, rest: 9, shop: 9 },
            enemies: ["re_ganning", "re_zhangfei", "re_huangzhong", "re_weiyan"],
            eliteEnemies: ["re_guanyu", "dianwei"],
            boss: "shen_guanyu",
            baseGold: 30,
        },
        {
            id: "act3",
            name: "第三关·终梦",
            floorNodes: [1, 4, 4, 4, 4, 4, 1],
            minFloorNodes: [1, 3, 2, 3, 2, 3, 1],
            nodeWeights: { battle: 45, elite: 20, event: 15, rest: 10, shop: 10 },
            enemies: ["re_simayi", "re_sunben", "dongzhuo", "re_yuanshao"],
            eliteEnemies: ["shen_zhaoyun", "shen_simayi"],
            boss: "shen_caocao",
            baseGold: 40,
        },
    ],
    startingDeck: [
        ["spade", 7, "sha"],
        ["heart", 10, "sha"],
        ["club", 4, "sha"],
        ["diamond", 6, "sha"],
        ["heart", 2, "shan"],
        ["diamond", 7, "shan"],
        ["club", 2, "shan"],
        ["heart", 3, "tao"],
        ["spade", 3, "guohe"],
        ["heart", 7, "wuzhong"],
        ["spade", 2, "bagua"],
        ["club", 6, "sha", null, ["annihilate"]],
    ],
    nodeNames: {
        battle: "战斗",
        elite: "精英",
        event: "事件",
        story: "剧情战斗",
        rest: "休息",
        shop: "商店",
        boss: "Boss",
    },
};

export default mengsanConfig;
