const translates = {
    zishu_boss_shuying: "子鼠",
    zishu_shuying: "子鼠",
    zishu_shuying_info: "出牌阶段限一次，你可以获得手牌数大于你的其他角色一张手牌，你可以重复此流程，直到你的手牌数为全场最多。",

    chenlong_boss_shuying: "辰龙",
    chenlong_shuying: "辰龙",
    chenlong_shuying_info: "限定技，出牌阶段，你可以失去任意点体力（至多为5），然后对一名其他角色造成等量的伤害。若你以此法进入濒死状态，则你将体力值回复至1，然后减少1点体力上限。",

    wuma_boss_shuying: "午马",
    wuma_shuying: "午马",
    wuma_shuying_info: "锁定技，你不能被翻面；你的阶段不能被跳过；当你成为其他角色使用锦囊牌的目标后，摸一张牌。",

    weiyang_boss_shuying: "未羊",
    weiyang_shuying: "未羊",
    weiyang_shuying_info: "出牌阶段限一次，你可以弃置任意张不同类型的牌，然后令至多等量角色回复1点体力。",

    shenhou_boss_shuying: "申猴",
    shenhou_shuying: "申猴",
    shenhou_shuying_info: "当你成为【杀】的目标时，你可以进行判定，若结果为红色，则此【杀】对你无效。",

    xvgou_boss_shuying: "戌狗",
    xvgou_shuying: "戌狗",
    xvgou_shuying_info: "锁定技，红色【杀】对你无效；你使用红色【杀】无距离限制且造成伤害+1.",

    heibaiwuchang_boss_shuying: "黑白无常",
    mizui_shuying: "迷醉",
    mizui_shuying_info: "锁定技，你的伤害牌造成伤害后，你随机弃置受伤角色的1张牌。",
    qiangzheng_shuying: "强征",
    qiangzheng_shuying_info: "锁定技，敌方角色的结束阶段，若其手牌数小于4，你获得其所有手牌。",
    xixing_shuying: "吸星",
    xixing_shuying_info: "锁定技，准备阶段，随机对敌方体力最多的一名角色造成2点雷电伤害，然后你回复等量体力",

    niutoumamian_boss_shuying: "牛头马面",
    shiyv_shuying: "施狱",
    shiyv_shuying_info: "锁定技，摸牌阶段，你放弃摸牌改为随机获得牌堆中每种花色的牌各一张。",
    manji_shuying: "蛮击",
    manji_shuying_info: "你使用【杀】指定单一目标后，你可以弃置该角色2张手牌。若其中有【杀】，你本次【杀】造成的伤害+1。",
    xiaoshou_shuying: "枭首",
    xiaoshou_shuying_info: "锁定技，准备阶段，你对随机一名敌方角色造成2点伤害",

    yvsai_boss_shuying: "鱼鳃",
    anchao_shuying: "暗潮",
    anchao_shuying_info: "锁定技，己方角色的回合结束时，若此回合该角色没有造成过伤害，则获得一个“暗潮”标记。己方回合开始时，若该角色有“暗潮”标记，则本回合摸牌阶段多摸X张牌且对敌方角色造成的伤害+X（X为“暗潮”标记数）",
    guixi_shuying: "鬼吸",
    guixi_shuying_info: "锁定技，当你受到伤害后，你进行一次判定，若结果为红色，你回复1点体力；若结果不为红色，你摸1张牌。",

    huangfeng_boss_shuying: "黄蜂",
    mingchong_shuying: "冥虫",
    mingchong_shuying_info: "锁定技，你死亡时，杀死你的角色随机弃置一半的牌。",
    duzhen_shuying: "毒针",
    duzhen_shuying_info: "锁定技，你使用牌指定单一敌方角色为目标后，该角色随机弃置1张牌（优先装备区的牌）。",

    riyeyoushen_boss_shuying: "日夜游神",
    huiyun_shuying: "晦运",
    huiyun_shuying_info: "出牌阶段限一次，你可以展示一名敌方角色的手牌，并弃置其中至多两张牌。然后你可以弃置一张与该角色弃置牌牌名相同的牌，对其造成2点伤害。",
    yezhong_shuying: "夜冢",
    yezhong_shuying_info: "锁定技，结束阶段，你进行一次判定并获得判定牌，若次牌为黑色，每名敌方角色随机弃1张手牌。",
    zhoucha_shuying: "昼刹",
    zhoucha_shuying_info: "锁定技，准备阶段，你进行一次判定并获得判定牌，若此牌为红色，你本回合使用【杀】的次数+1。",
    duane_shuying: "断恶",
    duane_shuying_info: "锁定技，敌方角色的弃牌阶段结束时，若其此阶段弃置了黑色牌，则该角色失去2点体力。",


    caocao_boss_shuying: "曹操",
    jianxiong_shuying: "奸雄",
    jianxiong_shuying_info: "当你受到伤害后，你可以获得对你造成伤害的牌并摸一张牌。",
    lingba_shuying: "凌霸",
    lingba_shuying_info: "锁定技，你的回合开始时，若你手牌数为全场最多，则对一名随机敌人造成1点伤害。若你手牌数大于等于你体力值的两倍，则改为对所有敌人造成伤害。",
    yishen_shuying: "疑神",
    yishen_shuying_info: "当你回复体力时，可以改为获得一名随机敌方角色一张随机装备。",

    simayi_boss_shuying: "司马懿",
    fankui_shuying: "反馈",
    fankui_shuying_info: "当你受到1点伤害后，你可以获得伤害来源的一张牌。",
    guicai_shuying: "鬼才",
    guicai_shuying_info: "当一名角色的判定牌生效前，你可以打出一张牌代替之。",
    langgu_shuying: "狼顾",
    langgu_shuying_info: "	锁定技，每回合限一次，当你获得其他角色的牌时，进行一次判定：若结果为黑桃，随机弃置其1张手牌，且视为此技能本回合未发动过。",
    yuanlv_shuying: "远虑",
    yuanlv_shuying_info: "当你使用锦囊牌对敌方角色造成伤害时，你可以防止该伤害，改为摸一张牌且该敌方角色对你造成1点伤害。",

    lvbu_boss_shuying: "吕布",
    wushuang_shuying: "无双",
    wushuang_shuying_info: "锁定技。①你使用的【杀】需两张【闪】才能抵消；与你进行【决斗】的角色每次需要打出两张【杀】。②每回合限1次，当你使用【杀】或【决斗】造成伤害时，若受伤角色没有使用或打出过【杀】或【闪】响应此牌，则此伤害+1。",
    shenij_shuying: "神戟",
    shenij_shuying_info: "判定阶段，你可以弃置两张手牌，然后弃置你判定区里的牌；摸牌阶段，你多摸两张牌；出牌阶段，你可以多使用一张【杀】，你的【杀】可以多指定一名角色为目标。",
    zhanjia_shuying: "战甲",
    zhanjia_shuying_info: "锁定技，每回合限一次，当你受到大于2点的伤害时，将此伤害减至2点，然后摸两张牌。",

    dongzhuo_boss_shuying: "董卓",
    jiuchi_shuying: "酒池",
    jiuchi_shuying_info: "你可以将一张黑桃手牌当【酒】使用。",
    roulin_shuying: "肉林",
    roulin_shuying_info: "锁定技，你对女性角色使用的【杀】和女性角色对你使用的【杀】均需使用两张【闪】才能抵消。",
    baonue_shuying: "暴虐",
    baonue_shuying_info: "锁定技，回合开始时，你摸X张牌并对至多X名角色造成1点伤害，然后你失去1点体力。X为你已损失体力且最大为3。",
    qubu_shuying: "驭布",
    qubu_shuying_info: "锁定技，当友方角色使用【杀】指定目标时，进行一次判定：若结果为黑桃，你对此【杀】的所有目标造成1点伤害。",


    shuishengonggong_boss_shuying: "水神共工",
    shuishen_shuying: "水神",
    shuishen_shuying_info: "锁定技，弃牌堆中，不同牌名的牌数达到4时，你回复体力时回复量+1；达到5时，摸牌阶段额外摸5张牌；达到9时，你造成伤害时伤害+1。",
    tuanliu_shuying: "湍流",
    tuanliu_shuying_info: "锁定技，结束阶段，若本回合进入弃牌堆的卡牌数量：大于4，你回复2点体力；大于5，你摸4张牌；大于9，你对所有敌方角色造成1点伤害。",
    juehong_shuying: "决洪",
    juehong_shuying_info: "锁定技，准备阶段，你令所有敌方角色自己弃置自己的装备区内的所有牌，若其装备区内没有牌，则改为随机弃置2张手牌",

    baiqi_boss_shuying: "白起",
    changsheng_shuying: "常胜",
    changsheng_shuying_info: "锁定技，你使用【杀】无距离限制。",
    shashen_shuying: "杀神",
    shashen_shuying_info: "你可以将手牌中的任意牌当【杀】使用或打出。你使用的【杀】造成伤害后，摸三张牌。",
    wuan_shuying: "武安",
    wuan_shuying_info: "锁定技，你可使用的【杀】的次数+3，【杀】造成的伤害+1。",

    kuafu_boss_shuying: "盘古",
    shenqu_shuying: "神躯",
    shenqu_shuying_info: "锁定技，当你受到伤害后，将所有红色手牌置于牌堆底，并摸等量的牌。",
    lieben_shuying: "烈奔",
    lieben_shuying_info: "锁定技，当你使用【杀】指定目标后，使用牌堆底的牌进行一次判定：若判定结果为红色，则此杀不计入出牌阶段使用次数且伤害+1。",
    yinjiang_shuying: "饮江",
    yinjiang_shuying_info: "锁定技，当你在出牌阶段摸牌后，获得牌堆底的1张牌。若该牌为红色，则对所有敌方角色造成1点伤害。当你在同一个阶段内以此法造成过两次活更多的伤害后，该技能失效直到回合结束。",
    zhuri_shuying: "逐日",
    zhuri_shuying_info: "锁定技，你使用红色牌时摸1张牌。当你成为【杀】或普通锦囊牌的目标后，结算完毕后将该牌放置在牌堆底。",

    shaohao_boss_shuying: "少昊",
    baiyi_shuying: "白仪",
    baiyi_shuying_info: "锁定技，每名敌方角色的回合开始时，若当前轮数小于3，你随机获得其1张牌；若当前轮数小于5，对其造成1点雷电伤害；若当前轮数小于7，其随机弃置1张牌。",
    shenen_shuying: "神恩",
    shenen_shuying_info: "锁定技，所有己方角色使用牌锁定技，所有己方角色使用牌没有距离限制。",


    xuannv_boss_shuying: "玄女",
    xuanlie_shuying: "玄烈",
    xuanlie_shuying_info: "锁定技，回合结束时，对所有本回合你获得过其牌的敌方角色依次造成1点伤害。",
    jiutian_shuying: "九天",
    jiutian_shuying_info: "锁定技，准备阶段，你获得所有敌方角色各1张手牌。若你以此法获得的牌包含2种颜色，则对所有你以此法获得其牌的敌方角色造成1点伤害。",
    dishi_shuying: "帝师",
    dishi_shuying_info: "当你使用【杀】或普通锦囊牌指定目标时，如果目标数为1，可以增加一个目标；如果目标数大于1，你可以减少一个目标。",

    hanba_boss_shuying: "旱魃",
    xinji_shuying: "心悸",
    xinji_shuying_info: "锁定技，当友方于回合外因弃置而失去手牌时，你对当前角色造成1点伤害。",
    zhiri_shuying: "炙日",
    zhiri_shuying_info: "锁定技，当敌方角色使用红色锦囊牌指定目标后，你摸1张牌。",
    fenshi_shuying: "焚世",
    fenshi_shuying_info: "锁定技，准备阶段，若你的手牌数小于体力值，则将手牌摸至于体力值相等；若你的手牌数大于体力值，则你对敌方角色造成共计X点伤害，点数随机分配（X为手牌数减体力值）。",

};

export default translates;
