const voices = {
    "#aotang_shuying1": "品汤消愁，情怨断念。",
    "#yunju_shuying1": "云雾缭绕，飓风意动。",
    "#guimei_shuying1": "鬼魅生惑，迷乱心神。",
    "#eli_shuying1": "豹贲之象，先锋之将。",
    "#bingyi_shuying1": "疑难杂病，入天则安。",
    "#suoxue_shuying1": "鸟穴虽小，亦有探索之地。",
    "#guixi_shuying1": "吸灵唤魂，游鱼而走。",
    "#anchao_shuying1": "暗潮涌动，感水知行。",
    "#duzhen_shuying1": "毒针入骨，百药难医。",
    "#mingchong_shuying1": "虫身虽小，威力无限。",
    "#xingpan_shuying1": "你的罪过，只能用刑偿还。",
    "#dianwei_shuying1": "阎罗立矩，斧钺杀威！",
    "#xuanpan_shuying1": "阎罗殿上杀威棒，判惩凶宵降猢狲！",
    "#xuanpan_shuying2": "本王要尔三更死，安能留汝到五更！",
    "#xixing_shuying1": "勾魂夺命，震骨吸星！",
    "#taiping_shuying1": "一见发财，天下太平！",
    "#qiangzheng_shuying1": "敲骨吸髓，征财索命！",
    "#mizui_shuying1": "凡间人世百般苦，唯有西方最极乐！",
    "#heibaiwuchang_boss_shuying:die": "索命鬼，终被捉！",
    "#xiaoshou_shuying1": "冥府鬼域，岂容尔等放肆！",
    "#manji_shuying1": "阴兵蛮霸，力大欺理！",
    "#shiyu_shuying1": "生财自有道，香烛狱中取！",
    "#guizhao_shuying1": "凡夫俗子，安识诡域之计！",
    "#niutoumamian_boss_shuying:die": "当牛做马数百载，只求为人一朝夕！",
    "#zhoucha_shuying1": "红煞蔽日，凶兵择噬！",
    "#yezhong_shuying1": "黑煞出冢，百鬼夜行！",
    "#huiyun_shuying1": "附骨之厄，追魂夺魄！",
    "#duane_shuying1": "幽冥之馈，尔等安敢弃之！",
    "#riyeyoushen_boss_shuying:die": "山河倒悬，阴阳相逆。",
    "#jizhou_shuying1": "鬼王凝咒，言出法随！",
    "#danshi_shuying1": "猛鬼食人，择魂而噬！",
    "#guiwang_boss_shuying:die": "阎罗殿里说枉死，忘川桥头叹奈何！",
};

export default voices;
