// 2026-10-03 灰机Wiki详情页主表。巨石为原始力量的衍生牌。
export const ironcladAdvancedEntries = [
    ["relentless_assault", "无情猛攻", 2, {damage:14, nextFreeAttack:true}, {damage:20}],
    ["howl_from_beyond", "彼岸咆哮", 3, {damage:16, all:true, exhaustReplay:true}, {damage:21}],
    ["stomp", "踩踏", 3, {damage:12, all:true, attackDiscount:true}, {damage:15}],
    ["battle_trance", "战斗专注", 0, {draw:3, stopDraw:true}, {draw:4}],
    ["infernal_blade", "地狱之刃", 1, {generateAttack:true, exhaust:true}, {cost:0}],
    ["drum_of_battle", "战鼓", 1, {draw:2, exhaustEnergy:2}, {exhaustEnergy:3}],
    ["eager", "跃跃欲试", 2, {energyPerAttack:true, stopEnergy:true}, {cost:1}],
    ["feel_no_pain", "无惧疼痛", 1, {power:"feelNoPain", exhaustBlock:3}, {exhaustBlock:4}],
    ["ferocity", "凶恶", 1, {power:"ferocity", vulnerableDraw:1}, {vulnerableDraw:2}],
    ["stone_armor", "岩石铠甲", 1, {power:"stoneArmor", plating:4}, {plating:6}],
    ["juggle", "杂耍", 1, {power:"juggle", juggle:1}, {innate:true}],
    ["stampede", "惊逃", 2, {power:"stampede", endAttack:1}, {cost:1}],
    ["feed", "狂宴", 1, {damage:10, feed:3, exhaust:true}, {damage:12, feed:4}],
    ["thrash", "痛殴", 1, {damage:4, hits:2, absorbAttack:true}, {damage:6}],
    ["bully", "凌虐", 3, {damage:15, negativeStrength:10}, {damage:20, negativeStrength:15}],
    ["unleash", "倾泻", "X", {topPlays:true, xBonus:0}, {xBonus:1}],
    ["primal_force", "原始力量", 0, {transformAttacks:true}, {boulderUpgrade:1}],
    ["twin_strike", "连环拳", 1, {doubleTap:1}, {doubleTap:2}],
    ["stoke", "添柴", 1, {stoke:true}, {generatedUpgrade:1}],
    ["battle_ready", "好勇斗狠", 1, {power:"battleReady", retrieveAttack:1}, {innate:true}],
    ["bodyguard", "肉盾", 1, {power:"bodyguard", bodyguard:1}, {cost:0}],
    ["hellraiser", "地狱狂徒", 2, {power:"hellraiser", autoStrike:1}, {cost:1}],
    ["dark_embrace", "黑暗之拥", 2, {power:"darkEmbrace", exhaustDraw:1}, {cost:1}],
    ["unshakable", "坚定不移", 2, {power:"unshakable", firstBlock:1}, {cost:1}],
    ["juggernaut", "势不可当", 2, {power:"juggernaut", blockDamage:6}, {blockDamage:8}],
    ["barricade", "壁垒", 3, {power:"barricade", barricade:1}, {cost:2}],
    ["dual_wield", "双持", 1, {copies:1}, {copies:2}],
    ["corruption", "腐化", 3, {power:"corruption", corruption:1}, {cost:2}],
    ["midnight", "午夜", 12, {damage:99, exhaustDiscount:true}, {damage:120}],
    ["rally", "群情激愤", 0, {damage:9, partyCopies:true}, {damage:13}],
    ["grapple", "擒拿", 1, {damage:7, grapple:5}, {damage:9, grapple:7}],
    ["boulder", "巨石", 1, {damage:16, generatedOnly:true}, {damage:20}],
].map(([id,title,cost,base,upgrade]) => [id,title,cost,{...base,advanced:true},{...upgrade}]);
